apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teste1234
  annotations:
    github.com/project-slug: Thiago0Carvalho/teste1234
spec:
  type: service
  lifecycle: unknown
  owner: acme-corp
